import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const makeIcon = (symbol) => ({ size = 18 }) => <span className="ui-icon" style={{ fontSize: size }}>{symbol}</span>;
const Bell=makeIcon('◌'), Search=makeIcon('⌕'), Eye=makeIcon('◉'), EyeOff=makeIcon('⊘'), ArrowDownToLine=makeIcon('⇩'), ArrowUpFromLine=makeIcon('⇧'), ArrowLeftRight=makeIcon('⇄'), Send=makeIcon('➤'), UsersRound=makeIcon('◉'), Home=makeIcon('⌂'), ChartNoAxesCombined=makeIcon('⌁'), WalletCards=makeIcon('▣'), UserRound=makeIcon('◯'), ChevronDown=makeIcon('⌄'), ArrowDownUp=makeIcon('↕'), ShieldCheck=makeIcon('✓'), Fingerprint=makeIcon('◎'), Settings=makeIcon('⚙'), MoreHorizontal=makeIcon('•••'), X=makeIcon('×'), Check=makeIcon('✓'), LockKeyhole=makeIcon('⌑'), ScanFace=makeIcon('◫'), CircleHelp=makeIcon('?');

const rate = 1500;
const API_BASE = 'https://wallet-api-7dom.onrender.com/api/v1';
const assets = {
  BTC:{ name:'Bitcoin', price:65000, icon:'₿', color:'#f7931a', change:2.84, data:'2,13 10,16 18,8 26,12 35,6 43,9 52,3 61,7 70,1' },
  ETH:{ name:'Ethereum', price:3540, icon:'♦', color:'#627eea', change:1.26, data:'2,16 10,10 18,14 26,7 35,11 43,4 52,9 61,2 70,5' },
  SOL:{ name:'Solana', price:142.8, icon:'≋', color:'#9a6bff', change:-0.74, data:'2,4 10,8 18,5 26,13 35,9 43,15 52,12 61,17 70,19' },
  USDT:{ name:'Tether USD', price:1, icon:'₮', color:'#26a17b', change:0.01, data:'2,11 10,11 18,10 26,11 35,10 43,11 52,10 61,11 70,10' },
  USD:{ name:'US Dollar', price:1, icon:'$', color:'#6e7d90', change:0, data:'2,11 70,11'},
  NGN:{ name:'Nigerian Naira', price:1/rate, icon:'₦', color:'#119a60', change:0, data:'2,11 70,11'}
};
const fmt = (num, decimals=2) => new Intl.NumberFormat('en-US',{minimumFractionDigits:decimals,maximumFractionDigits:decimals}).format(num);
const money = (v,currency='USD') => currency==='NGN' ? `₦${fmt(v*rate)}` : `$${fmt(v)}`;
function AssetIcon({symbol, small=false}) { const a=assets[symbol]; return <span className={'asset-icon '+(small?'small':'')} style={{background:a.color}}>{a.icon}</span> }
function Spark({asset}) { let a=assets[asset]; return <svg className="spark" viewBox="0 0 72 22" preserveAspectRatio="none"><polyline points={a.data} fill="none" stroke={a.change<0?'#f6465d':'#0ecb81'} strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" /></svg> }

function App(){
 const [tab,setTab]=useState('Home'), [market,setMarket]=useState('Hot'), [visible,setVisible]=useState(true), [currency,setCurrency]=useState('USD'), [modal,setModal]=useState(null), [from,setFrom]=useState('USDT'), [to,setTo]=useState('NGN'), [amount,setAmount]=useState('100'), [toast,setToast]=useState(''), [session,setSession]=useState(()=>JSON.parse(localStorage.getItem('wallet_session')||'null')), [balances,setBalances]=useState([]), [history,setHistory]=useState([]), [refresh,setRefresh]=useState(0);
 const user=session?.user;
 const completeAuth=(next)=>{localStorage.setItem('wallet_session',JSON.stringify(next));setSession(next);setToast(`Welcome, ${next.user.fullName.split(' ')[0]}`);setTimeout(()=>setToast(''),2800)};
 useEffect(()=>{if(!session)return;const headers={Authorization:`Bearer ${session.accessToken}`};Promise.all([fetch(`${API_BASE}/wallet/balance?userId=${session.user.id}`,{headers}),fetch(`${API_BASE}/transactions/history?userId=${session.user.id}`,{headers})]).then(async([wallet,transactions])=>{if(wallet.ok)setBalances((await wallet.json()).balances||[]);if(transactions.ok)setHistory((await transactions.json()).transactions||[])}).catch(()=>setToast('Unable to refresh wallet data'));},[session,refresh]);
 const total=balances.length?balances.reduce((sum,item)=>sum+(Number(item.balance)||0)*(assets[item.asset]?.price||0),0):user?0:2450, display=currency==='NGN'?total*rate:total;
 const converted=useMemo(()=>{ const usd=Number(amount||0)*assets[from].price; return usd/assets[to].price },[amount,from,to]);
 const changeTab = (next) => {setTab(next); if(next==='Convert') setTimeout(()=>document.querySelector('.converter')?.scrollIntoView({behavior:'smooth'}),10)};
 const action=(title)=> { if(title==='Convert') {setTab('Convert'); setTimeout(()=>document.querySelector('.converter')?.scrollIntoView({behavior:'smooth'}),10)} else setModal(title==='Withdraw'?'security':'action') };
 const confirm=()=>{setModal(null);setToast('Conversion request secured and submitted');setTimeout(()=>setToast(''),2800)};
 const executeConvert=async()=>{if(!session){setTab('Profile');setToast('Sign in to convert');return}try{const response=await fetch(`${API_BASE}/wallet/convert`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.accessToken}`},body:JSON.stringify({sourceAsset:from,targetAsset:to,sourceAmount:Number(amount)})});const data=await response.json();if(!response.ok)throw new Error(data.message||'Conversion failed');setToast(`Converted ${data.sourceAmount} ${data.sourceCurrency}`);setRefresh(value=>value+1)}catch(error){setToast(error.message||'Conversion failed')}};
 return <main className="app-shell">
  <div className="status"><span>9:41</span><span>● ● ● &nbsp;▰</span></div>
  <header><button className="avatar" onClick={()=>setTab('Profile')}>{user?.fullName?.split(' ').map(x=>x[0]).join('').slice(0,2)||'AO'}</button><div className="kyc"><ShieldCheck size={13}/> {user?user.kycStatus:'Demo mode'}</div><button className="search"><Search size={17}/><span>Search assets</span></button><button className="icon-button"><Bell size={20}/><i/></button></header>
  <section className="balance-card"><div className="balance-head"><span>Total assets</span><button onClick={()=>setVisible(!visible)}>{visible?<Eye size={17}/>:<EyeOff size={17}/>}</button><span className="balance-menu"><MoreHorizontal size={19}/></span></div><div className="balance-value">{visible?money(display,currency):'••••••••'}</div><div className="naira-line">{visible ? currency==='USD' ? `≈ ₦${fmt(total*rate)}` : `≈ $${fmt(total)}` : '••••••••'}</div><div className="pnl"><span>24h P&L</span><b>+$42.60 <em>+1.77%</em></b></div><div className="card-footer"><span>Spot account</span><span>View assets <ChevronDown size={14}/></span></div></section>
  <section className="actions">{[[ArrowDownToLine,'Deposit'],[ArrowUpFromLine,'Withdraw'],[ArrowLeftRight,'Convert'],[Send,'Transfer'],[UsersRound,'P2P']].map(([Icon,label])=><button key={label} onClick={()=>action(label)}><span><Icon size={19}/></span>{label}</button>)}</section>
  <section className="section-title"><div><h2>Markets</h2><p>Top movers right now</p></div><button onClick={()=>setTab('Markets')}>View all</button></section>
  <div className="market-tabs">{['Hot','Gainers','Losers','24h Volume'].map(x=><button className={market===x?'active':''} onClick={()=>setMarket(x)} key={x}>{x}</button>)}</div>
  <section className="watchlist">{['BTC','ETH','SOL','USDT'].map((ticker,i)=>{let a=assets[ticker], neg=market==='Losers'?i%2===0: a.change<0; let c=neg?-Math.abs(a.change):Math.abs(a.change);return <div className="market-row" key={ticker}><AssetIcon symbol={ticker}/><div className="coin-name"><b>{ticker}</b><small>{a.name}</small></div><div className="price"><b>${fmt(a.price,a.price<10?4:2)}</b><small>₦{fmt(a.price*rate, a.price<10?2:0)}</small></div><Spark asset={ticker}/><span className={'change '+(c<0?'down':'')}>{c>0?'+':''}{fmt(c)}%</span></div>})}</section>
  {user&&<section className="activity"><div className="section-title"><div><h2>Recent activity</h2><p>{balances.length?`${balances.length} live asset balance${balances.length>1?'s':''}`:'No funded assets yet'}</p></div></div>{history.slice(0,3).map(item=><div className="activity-row" key={item.id}><span className="activity-dot"/><div><b>{item.sourceCurrency} → {item.targetCurrency}</b><small>{item.statusMessage||item.status}</small></div><strong>{item.status}</strong></div>)}</section>}
  <section className="converter" id="convert"><div className="converter-title"><div><span className="amber-dot"/> Instant convert</div><button onClick={()=>setModal('rate')}><CircleHelp size={18}/></button></div><p>Zero-fee conversions at the current rate</p><div className="convert-box"><label>From</label><div className="input-row"><select value={from} onChange={e=>setFrom(e.target.value)}>{Object.keys(assets).map(x=><option key={x}>{x}</option>)}</select><input value={amount} onChange={e=>setAmount(e.target.value.replace(/[^0-9.]/g,''))} inputMode="decimal"/><span className="unit">{from}</span></div></div>
  <button className="swap" onClick={()=>{let x=from;setFrom(to);setTo(x)}}><ArrowDownUp size={18}/></button>
  <div className="convert-box to"><label>To</label><div className="input-row"><select value={to} onChange={e=>setTo(e.target.value)}>{Object.keys(assets).map(x=><option key={x}>{x}</option>)}</select><div className="output">{fmt(converted, converted<1?6:2)}</div><span className="unit">{to}</span></div></div>
  <div className="rate"><span>Live exchange rate</span><b>1 {from} = {fmt(assets[from].price/assets[to].price, to==='NGN'?2:6)} {to}</b></div><button className="convert-btn" onClick={executeConvert}>Convert instantly <ArrowLeftRight size={18}/></button></section>
  {tab==='Profile'&&(user?<section className="profile-panel"><div className="profile-top"><div className="avatar big">{user.fullName.split(' ').map(x=>x[0]).join('').slice(0,2)}</div><div><h3>{user.fullName}</h3><p>{user.email}</p></div><ChevronDown size={18}/></div><div className="profile-status"><div><ShieldCheck/><span><b>{user.kycStatus} verification</b><small>Complete KYC before wallet movement</small></span><Check size={17}/></div><div><LockKeyhole/><span><b>Security score: strong</b><small>Token session active</small></span><Settings size={17}/></div></div><div className="pref"><span>Display currency</span><button onClick={()=>setCurrency(currency==='USD'?'NGN':'USD')}>{currency==='USD'?'$ USD':'₦ NGN'} <ChevronDown size={15}/></button></div><button className="signout" onClick={()=>{localStorage.removeItem('wallet_session');setSession(null)}}>Sign out</button></section>:<AuthPanel onAuth={completeAuth}/>) }
  <nav>{[[Home,'Home'],[ChartNoAxesCombined,'Markets'],[ArrowLeftRight,'Convert'],[WalletCards,'Wallet'],[UserRound,'Profile']].map(([Icon,name])=><button className={tab===name?'selected':''} onClick={()=>changeTab(name)} key={name}><Icon size={21}/><span>{name}</span></button>)}</nav>
  {toast&&<div className="toast"><Check size={17}/>{toast}</div>}
  {modal&&<Modal type={modal} close={()=>setModal(null)} confirm={confirm}/>} 
 </main>
}
function AuthPanel({onAuth}){const [mode,setMode]=useState('login'),[form,setForm]=useState({fullName:'',email:'',phoneNumber:'',country:'NG',password:''}),[error,setError]=useState(''),[loading,setLoading]=useState(false);const update=e=>setForm({...form,[e.target.name]:e.target.value});const submit=async e=>{e.preventDefault();setError('');setLoading(true);try{const payload=mode==='login'?{email:form.email,password:form.password}:form;const response=await fetch(`${API_BASE}/auth/${mode==='login'?'login':'register'}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw new Error(data.message||'Unable to authenticate');onAuth(data)}catch(err){setError(err.message||'Network error')}finally{setLoading(false)}};return <section className="profile-panel auth-panel"><div className="auth-heading"><div className="modal-icon"><LockKeyhole/></div><h3>{mode==='login'?'Welcome back':'Create your wallet'}</h3><p>Securely connected to the live wallet API.</p></div><form onSubmit={submit}>{mode==='register'&&<><input name="fullName" placeholder="Full name" value={form.fullName} onChange={update} required/><input name="phoneNumber" placeholder="Phone number" value={form.phoneNumber} onChange={update} required/></>}<input name="email" type="email" placeholder="Email address" value={form.email} onChange={update} required/><input name="password" type="password" placeholder="Password (12+ characters)" minLength="12" value={form.password} onChange={update} required/>{error&&<p className="auth-error">{error}</p>}<button className="primary" disabled={loading}>{loading?'Please wait…':mode==='login'?'Sign in':'Create account'}</button></form><button className="auth-switch" onClick={()=>{setMode(mode==='login'?'register':'login');setError('')}}>{mode==='login'?'New here? Create an account':'Already have an account? Sign in'}</button></section>}
function Modal({type,close,confirm}){const [pin,setPin]=useState('');const security=type==='security';return <div className="overlay"><div className="modal"><button className="close" onClick={close}><X size={20}/></button>{security?<><div className="modal-icon"><LockKeyhole/></div><h3>Confirm with security check</h3><p>Enter your 4-digit trading PIN to continue.</p><input className="pin" maxLength="4" value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,''))} placeholder="••••" inputMode="numeric"/><button className="primary" disabled={pin.length<4} onClick={confirm}>Continue</button><button className="bio"><Fingerprint size={19}/> Use biometric verification</button></>:<><div className="modal-icon"><ScanFace/></div><h3>{type==='Withdraw'?'Secure withdrawal':'Ready when you are'}</h3><p>{type==='rate'?'Rates refresh continuously. Your final rate is locked at confirmation.':'This action is protected by PIN, two-factor authentication and biometric checks.'}</p><button className="primary" onClick={close}>Got it</button></>}</div></div>}
createRoot(document.getElementById('root')).render(<App/>);
